### ISSUE TITLE
Remove Github Pages Warning

### ISSUE THREAD

**Issue by djallits** [xipasduarte/satis#1]
Using your project as a boilerplate, and I wanted to point out that Github Pages now supports SSL for Custom Domains as mentioned in the [Custom domains on GitHub Pages gain support for HTTPS](https://blog.github.com/2018-05-01-github-pages-custom-domains-https/)  article.

**Comment by xipasduarte** [comment]
Thank you. That was why I didn't use it in the first place. Hope the repo helped you in saving some time 😉
